/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiCspReportRouteImport } from './routes/api.csp-report'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSizeSettingsRouteImport } from './routes/admin.size-settings'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMfaRouteImport } from './routes/admin.mfa'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMediaLibraryRouteImport } from './routes/admin.media-library'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCourierRouteImport } from './routes/admin.courier'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as SiteWishlistRouteImport } from './routes/_site.wishlist'
import { Route as SiteTrackRouteImport } from './routes/_site.track'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteSizeGuideRouteImport } from './routes/_site.size-guide'
import { Route as SiteShopRouteImport } from './routes/_site.shop'
import { Route as SiteReturnPolicyRouteImport } from './routes/_site.return-policy'
import { Route as SitePrivacyPolicyRouteImport } from './routes/_site.privacy-policy'
import { Route as SitePaymentPolicyRouteImport } from './routes/_site.payment-policy'
import { Route as SiteOrdersRouteImport } from './routes/_site.orders'
import { Route as SiteOrderSuccessRouteImport } from './routes/_site.order-success'
import { Route as SiteLoginRouteImport } from './routes/_site.login'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteEidStyleGuideRouteImport } from './routes/_site.eid-style-guide'
import { Route as SiteDeliveryPolicyRouteImport } from './routes/_site.delivery-policy'
import { Route as SiteCustomSizePolicyRouteImport } from './routes/_site.custom-size-policy'
import { Route as SiteCookiePolicyRouteImport } from './routes/_site.cookie-policy'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteAuthenticityPolicyRouteImport } from './routes/_site.authenticity-policy'
import { Route as SiteAccountRouteImport } from './routes/_site.account'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteSplatRouteImport } from './routes/_site.$'
import { Route as SiteAccountIndexRouteImport } from './routes/_site.account.index'
import { Route as ApiWebhookSteadfastRouteImport } from './routes/api.webhook.steadfast'
import { Route as ApiWebhookPathaoRouteImport } from './routes/api.webhook.pathao'
import { Route as SiteProductSlugRouteImport } from './routes/_site.product.$slug'
import { Route as SiteOrdersIdRouteImport } from './routes/_site.orders.$id'
import { Route as SiteAccountSecurityRouteImport } from './routes/_site.account.security'
import { Route as SiteAccountProfileRouteImport } from './routes/_site.account.profile'
import { Route as SiteAccountMeasurementsRouteImport } from './routes/_site.account.measurements'
import { Route as SiteAccountAddressesRouteImport } from './routes/_site.account.addresses'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSizeSettingsRoute = AdminSizeSettingsRouteImport.update({
  id: '/size-settings',
  path: '/size-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaLibraryRoute = AdminMediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourierRoute = AdminCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const SiteWishlistRoute = SiteWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrackRoute = SiteTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSizeGuideRoute = SiteSizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReturnPolicyRoute = SiteReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyPolicyRoute = SitePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SitePaymentPolicyRoute = SitePaymentPolicyRouteImport.update({
  id: '/payment-policy',
  path: '/payment-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrdersRoute = SiteOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrderSuccessRoute = SiteOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEidStyleGuideRoute = SiteEidStyleGuideRouteImport.update({
  id: '/eid-style-guide',
  path: '/eid-style-guide',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDeliveryPolicyRoute = SiteDeliveryPolicyRouteImport.update({
  id: '/delivery-policy',
  path: '/delivery-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCustomSizePolicyRoute = SiteCustomSizePolicyRouteImport.update({
  id: '/custom-size-policy',
  path: '/custom-size-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCookiePolicyRoute = SiteCookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuthenticityPolicyRoute = SiteAuthenticityPolicyRouteImport.update({
  id: '/authenticity-policy',
  path: '/authenticity-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSplatRoute = SiteSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountIndexRoute = SiteAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteAccountRoute,
} as any)
const ApiWebhookSteadfastRoute = ApiWebhookSteadfastRouteImport.update({
  id: '/api/webhook/steadfast',
  path: '/api/webhook/steadfast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPathaoRoute = ApiWebhookPathaoRouteImport.update({
  id: '/api/webhook/pathao',
  path: '/api/webhook/pathao',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteProductSlugRoute = SiteProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrdersIdRoute = SiteOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SiteOrdersRoute,
} as any)
const SiteAccountSecurityRoute = SiteAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SiteAccountRoute,
} as any)
const SiteAccountProfileRoute = SiteAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SiteAccountRoute,
} as any)
const SiteAccountMeasurementsRoute = SiteAccountMeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => SiteAccountRoute,
} as any)
const SiteAccountAddressesRoute = SiteAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => SiteAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof SiteSplatRoute
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRouteWithChildren
  '/authenticity-policy': typeof SiteAuthenticityPolicyRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/cookie-policy': typeof SiteCookiePolicyRoute
  '/custom-size-policy': typeof SiteCustomSizePolicyRoute
  '/delivery-policy': typeof SiteDeliveryPolicyRoute
  '/eid-style-guide': typeof SiteEidStyleGuideRoute
  '/faq': typeof SiteFaqRoute
  '/login': typeof SiteLoginRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/orders': typeof SiteOrdersRouteWithChildren
  '/payment-policy': typeof SitePaymentPolicyRoute
  '/privacy-policy': typeof SitePrivacyPolicyRoute
  '/return-policy': typeof SiteReturnPolicyRoute
  '/shop': typeof SiteShopRoute
  '/size-guide': typeof SiteSizeGuideRoute
  '/terms': typeof SiteTermsRoute
  '/track': typeof SiteTrackRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media-library': typeof AdminMediaLibraryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/size-settings': typeof AdminSizeSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/account/addresses': typeof SiteAccountAddressesRoute
  '/account/measurements': typeof SiteAccountMeasurementsRoute
  '/account/profile': typeof SiteAccountProfileRoute
  '/account/security': typeof SiteAccountSecurityRoute
  '/orders/$id': typeof SiteOrdersIdRoute
  '/product/$slug': typeof SiteProductSlugRoute
  '/api/webhook/pathao': typeof ApiWebhookPathaoRoute
  '/api/webhook/steadfast': typeof ApiWebhookSteadfastRoute
  '/account/': typeof SiteAccountIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof SiteSplatRoute
  '/about': typeof SiteAboutRoute
  '/authenticity-policy': typeof SiteAuthenticityPolicyRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/cookie-policy': typeof SiteCookiePolicyRoute
  '/custom-size-policy': typeof SiteCustomSizePolicyRoute
  '/delivery-policy': typeof SiteDeliveryPolicyRoute
  '/eid-style-guide': typeof SiteEidStyleGuideRoute
  '/faq': typeof SiteFaqRoute
  '/login': typeof SiteLoginRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/orders': typeof SiteOrdersRouteWithChildren
  '/payment-policy': typeof SitePaymentPolicyRoute
  '/privacy-policy': typeof SitePrivacyPolicyRoute
  '/return-policy': typeof SiteReturnPolicyRoute
  '/shop': typeof SiteShopRoute
  '/size-guide': typeof SiteSizeGuideRoute
  '/terms': typeof SiteTermsRoute
  '/track': typeof SiteTrackRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media-library': typeof AdminMediaLibraryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/size-settings': typeof AdminSizeSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/addresses': typeof SiteAccountAddressesRoute
  '/account/measurements': typeof SiteAccountMeasurementsRoute
  '/account/profile': typeof SiteAccountProfileRoute
  '/account/security': typeof SiteAccountSecurityRoute
  '/orders/$id': typeof SiteOrdersIdRoute
  '/product/$slug': typeof SiteProductSlugRoute
  '/api/webhook/pathao': typeof ApiWebhookPathaoRoute
  '/api/webhook/steadfast': typeof ApiWebhookSteadfastRoute
  '/account': typeof SiteAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/$': typeof SiteSplatRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/account': typeof SiteAccountRouteWithChildren
  '/_site/authenticity-policy': typeof SiteAuthenticityPolicyRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/cookie-policy': typeof SiteCookiePolicyRoute
  '/_site/custom-size-policy': typeof SiteCustomSizePolicyRoute
  '/_site/delivery-policy': typeof SiteDeliveryPolicyRoute
  '/_site/eid-style-guide': typeof SiteEidStyleGuideRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/order-success': typeof SiteOrderSuccessRoute
  '/_site/orders': typeof SiteOrdersRouteWithChildren
  '/_site/payment-policy': typeof SitePaymentPolicyRoute
  '/_site/privacy-policy': typeof SitePrivacyPolicyRoute
  '/_site/return-policy': typeof SiteReturnPolicyRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/size-guide': typeof SiteSizeGuideRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/track': typeof SiteTrackRoute
  '/_site/wishlist': typeof SiteWishlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media-library': typeof AdminMediaLibraryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/size-settings': typeof AdminSizeSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/account/addresses': typeof SiteAccountAddressesRoute
  '/_site/account/measurements': typeof SiteAccountMeasurementsRoute
  '/_site/account/profile': typeof SiteAccountProfileRoute
  '/_site/account/security': typeof SiteAccountSecurityRoute
  '/_site/orders/$id': typeof SiteOrdersIdRoute
  '/_site/product/$slug': typeof SiteProductSlugRoute
  '/api/webhook/pathao': typeof ApiWebhookPathaoRoute
  '/api/webhook/steadfast': typeof ApiWebhookSteadfastRoute
  '/_site/account/': typeof SiteAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$'
    | '/about'
    | '/account'
    | '/authenticity-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/custom-size-policy'
    | '/delivery-policy'
    | '/eid-style-guide'
    | '/faq'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/payment-policy'
    | '/privacy-policy'
    | '/return-policy'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/track'
    | '/wishlist'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/media-library'
    | '/admin/messages'
    | '/admin/mfa'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/policies'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/size-settings'
    | '/admin/staff'
    | '/api/csp-report'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/update-password'
    | '/admin/'
    | '/account/addresses'
    | '/account/measurements'
    | '/account/profile'
    | '/account/security'
    | '/orders/$id'
    | '/product/$slug'
    | '/api/webhook/pathao'
    | '/api/webhook/steadfast'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$'
    | '/about'
    | '/authenticity-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/custom-size-policy'
    | '/delivery-policy'
    | '/eid-style-guide'
    | '/faq'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/payment-policy'
    | '/privacy-policy'
    | '/return-policy'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/track'
    | '/wishlist'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/media-library'
    | '/admin/messages'
    | '/admin/mfa'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/policies'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/size-settings'
    | '/admin/staff'
    | '/api/csp-report'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/update-password'
    | '/'
    | '/admin'
    | '/account/addresses'
    | '/account/measurements'
    | '/account/profile'
    | '/account/security'
    | '/orders/$id'
    | '/product/$slug'
    | '/api/webhook/pathao'
    | '/api/webhook/steadfast'
    | '/account'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_site/$'
    | '/_site/about'
    | '/_site/account'
    | '/_site/authenticity-policy'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/contact'
    | '/_site/cookie-policy'
    | '/_site/custom-size-policy'
    | '/_site/delivery-policy'
    | '/_site/eid-style-guide'
    | '/_site/faq'
    | '/_site/login'
    | '/_site/order-success'
    | '/_site/orders'
    | '/_site/payment-policy'
    | '/_site/privacy-policy'
    | '/_site/return-policy'
    | '/_site/shop'
    | '/_site/size-guide'
    | '/_site/terms'
    | '/_site/track'
    | '/_site/wishlist'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/media-library'
    | '/admin/messages'
    | '/admin/mfa'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/policies'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/size-settings'
    | '/admin/staff'
    | '/api/csp-report'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/update-password'
    | '/_site/'
    | '/admin/'
    | '/_site/account/addresses'
    | '/_site/account/measurements'
    | '/_site/account/profile'
    | '/_site/account/security'
    | '/_site/orders/$id'
    | '/_site/product/$slug'
    | '/api/webhook/pathao'
    | '/api/webhook/steadfast'
    | '/_site/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCspReportRoute: typeof ApiCspReportRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  ApiWebhookPathaoRoute: typeof ApiWebhookPathaoRoute
  ApiWebhookSteadfastRoute: typeof ApiWebhookSteadfastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csp-report': {
      id: '/api/csp-report'
      path: '/api/csp-report'
      fullPath: '/api/csp-report'
      preLoaderRoute: typeof ApiCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/size-settings': {
      id: '/admin/size-settings'
      path: '/size-settings'
      fullPath: '/admin/size-settings'
      preLoaderRoute: typeof AdminSizeSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mfa': {
      id: '/admin/mfa'
      path: '/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media-library': {
      id: '/admin/media-library'
      path: '/media-library'
      fullPath: '/admin/media-library'
      preLoaderRoute: typeof AdminMediaLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courier': {
      id: '/admin/courier'
      path: '/courier'
      fullPath: '/admin/courier'
      preLoaderRoute: typeof AdminCourierRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/wishlist': {
      id: '/_site/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof SiteWishlistRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/track': {
      id: '/_site/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof SiteTrackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/size-guide': {
      id: '/_site/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SiteSizeGuideRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/return-policy': {
      id: '/_site/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof SiteReturnPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy-policy': {
      id: '/_site/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof SitePrivacyPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/payment-policy': {
      id: '/_site/payment-policy'
      path: '/payment-policy'
      fullPath: '/payment-policy'
      preLoaderRoute: typeof SitePaymentPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/orders': {
      id: '/_site/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof SiteOrdersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/order-success': {
      id: '/_site/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof SiteOrderSuccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/eid-style-guide': {
      id: '/_site/eid-style-guide'
      path: '/eid-style-guide'
      fullPath: '/eid-style-guide'
      preLoaderRoute: typeof SiteEidStyleGuideRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/delivery-policy': {
      id: '/_site/delivery-policy'
      path: '/delivery-policy'
      fullPath: '/delivery-policy'
      preLoaderRoute: typeof SiteDeliveryPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/custom-size-policy': {
      id: '/_site/custom-size-policy'
      path: '/custom-size-policy'
      fullPath: '/custom-size-policy'
      preLoaderRoute: typeof SiteCustomSizePolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cookie-policy': {
      id: '/_site/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof SiteCookiePolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/authenticity-policy': {
      id: '/_site/authenticity-policy'
      path: '/authenticity-policy'
      fullPath: '/authenticity-policy'
      preLoaderRoute: typeof SiteAuthenticityPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account': {
      id: '/_site/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/$': {
      id: '/_site/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SiteSplatRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account/': {
      id: '/_site/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof SiteAccountIndexRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/api/webhook/steadfast': {
      id: '/api/webhook/steadfast'
      path: '/api/webhook/steadfast'
      fullPath: '/api/webhook/steadfast'
      preLoaderRoute: typeof ApiWebhookSteadfastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/pathao': {
      id: '/api/webhook/pathao'
      path: '/api/webhook/pathao'
      fullPath: '/api/webhook/pathao'
      preLoaderRoute: typeof ApiWebhookPathaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/product/$slug': {
      id: '/_site/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof SiteProductSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/orders/$id': {
      id: '/_site/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof SiteOrdersIdRouteImport
      parentRoute: typeof SiteOrdersRoute
    }
    '/_site/account/security': {
      id: '/_site/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof SiteAccountSecurityRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/_site/account/profile': {
      id: '/_site/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof SiteAccountProfileRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/_site/account/measurements': {
      id: '/_site/account/measurements'
      path: '/measurements'
      fullPath: '/account/measurements'
      preLoaderRoute: typeof SiteAccountMeasurementsRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/_site/account/addresses': {
      id: '/_site/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof SiteAccountAddressesRouteImport
      parentRoute: typeof SiteAccountRoute
    }
  }
}

interface SiteAccountRouteChildren {
  SiteAccountAddressesRoute: typeof SiteAccountAddressesRoute
  SiteAccountMeasurementsRoute: typeof SiteAccountMeasurementsRoute
  SiteAccountProfileRoute: typeof SiteAccountProfileRoute
  SiteAccountSecurityRoute: typeof SiteAccountSecurityRoute
  SiteAccountIndexRoute: typeof SiteAccountIndexRoute
}

const SiteAccountRouteChildren: SiteAccountRouteChildren = {
  SiteAccountAddressesRoute: SiteAccountAddressesRoute,
  SiteAccountMeasurementsRoute: SiteAccountMeasurementsRoute,
  SiteAccountProfileRoute: SiteAccountProfileRoute,
  SiteAccountSecurityRoute: SiteAccountSecurityRoute,
  SiteAccountIndexRoute: SiteAccountIndexRoute,
}

const SiteAccountRouteWithChildren = SiteAccountRoute._addFileChildren(
  SiteAccountRouteChildren,
)

interface SiteOrdersRouteChildren {
  SiteOrdersIdRoute: typeof SiteOrdersIdRoute
}

const SiteOrdersRouteChildren: SiteOrdersRouteChildren = {
  SiteOrdersIdRoute: SiteOrdersIdRoute,
}

const SiteOrdersRouteWithChildren = SiteOrdersRoute._addFileChildren(
  SiteOrdersRouteChildren,
)

interface SiteRouteChildren {
  SiteSplatRoute: typeof SiteSplatRoute
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAccountRoute: typeof SiteAccountRouteWithChildren
  SiteAuthenticityPolicyRoute: typeof SiteAuthenticityPolicyRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCookiePolicyRoute: typeof SiteCookiePolicyRoute
  SiteCustomSizePolicyRoute: typeof SiteCustomSizePolicyRoute
  SiteDeliveryPolicyRoute: typeof SiteDeliveryPolicyRoute
  SiteEidStyleGuideRoute: typeof SiteEidStyleGuideRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteOrderSuccessRoute: typeof SiteOrderSuccessRoute
  SiteOrdersRoute: typeof SiteOrdersRouteWithChildren
  SitePaymentPolicyRoute: typeof SitePaymentPolicyRoute
  SitePrivacyPolicyRoute: typeof SitePrivacyPolicyRoute
  SiteReturnPolicyRoute: typeof SiteReturnPolicyRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteSizeGuideRoute: typeof SiteSizeGuideRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTrackRoute: typeof SiteTrackRoute
  SiteWishlistRoute: typeof SiteWishlistRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductSlugRoute: typeof SiteProductSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteSplatRoute: SiteSplatRoute,
  SiteAboutRoute: SiteAboutRoute,
  SiteAccountRoute: SiteAccountRouteWithChildren,
  SiteAuthenticityPolicyRoute: SiteAuthenticityPolicyRoute,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCookiePolicyRoute: SiteCookiePolicyRoute,
  SiteCustomSizePolicyRoute: SiteCustomSizePolicyRoute,
  SiteDeliveryPolicyRoute: SiteDeliveryPolicyRoute,
  SiteEidStyleGuideRoute: SiteEidStyleGuideRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteOrderSuccessRoute: SiteOrderSuccessRoute,
  SiteOrdersRoute: SiteOrdersRouteWithChildren,
  SitePaymentPolicyRoute: SitePaymentPolicyRoute,
  SitePrivacyPolicyRoute: SitePrivacyPolicyRoute,
  SiteReturnPolicyRoute: SiteReturnPolicyRoute,
  SiteShopRoute: SiteShopRoute,
  SiteSizeGuideRoute: SiteSizeGuideRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteTrackRoute: SiteTrackRoute,
  SiteWishlistRoute: SiteWishlistRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductSlugRoute: SiteProductSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCourierRoute: typeof AdminCourierRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaLibraryRoute: typeof AdminMediaLibraryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminMfaRoute: typeof AdminMfaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSizeSettingsRoute: typeof AdminSizeSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCourierRoute: AdminCourierRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaLibraryRoute: AdminMediaLibraryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminMfaRoute: AdminMfaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSizeSettingsRoute: AdminSizeSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCspReportRoute: ApiCspReportRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  ApiWebhookPathaoRoute: ApiWebhookPathaoRoute,
  ApiWebhookSteadfastRoute: ApiWebhookSteadfastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
