-- Production migration version: 20260826083442.
-- Premium, non-destructive product image pipeline.
--
-- The private bucket stores exactly what the admin selected. The public bucket
-- stores a browser-readable delivery master (the original when already ideal,
-- otherwise a high-quality WebP normalization). Only service-role code mints
-- signed upload URLs; neither bucket has client write policies.

-- Keep public delivery masters web-native and large enough for high-resolution
-- product zoom. Runtime responsive AVIF/WebP variants are generated by Vercel.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'product-media', 'product-media', true, 15728640,
  ARRAY['image/png','image/jpeg','image/webp','image/avif','image/gif']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Private non-destructive originals. SVG, PDF, PSD and camera RAW deliberately
-- remain document/creative-workflow formats rather than product-photo inputs.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'product-media-originals', 'product-media-originals', false, 31457280,
  ARRAY[
    'image/png','image/jpeg','image/webp','image/avif','image/gif',
    'image/bmp','image/heic','image/heif','image/tiff'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- The bucket was raised to 15 MB in 20260725165625, but the original table
-- constraint still capped catalogue rows at 5 MB. Bring both limits into sync.
ALTER TABLE public.media_assets
  DROP CONSTRAINT IF EXISTS media_assets_size_bytes_check;
ALTER TABLE public.media_assets
  DROP CONSTRAINT IF EXISTS media_assets_size_bytes_web_limit;
ALTER TABLE public.media_assets
  ADD CONSTRAINT media_assets_size_bytes_web_limit
    CHECK (size_bytes BETWEEN 0 AND 15728640);

ALTER TABLE public.media_assets
  ADD COLUMN IF NOT EXISTS source_storage_path text,
  ADD COLUMN IF NOT EXISTS source_file_name text,
  ADD COLUMN IF NOT EXISTS source_content_type text,
  ADD COLUMN IF NOT EXISTS source_size_bytes integer,
  ADD COLUMN IF NOT EXISTS processing_mode text NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS suggested_focal_x numeric,
  ADD COLUMN IF NOT EXISTS suggested_focal_y numeric;

ALTER TABLE public.media_assets
  ADD CONSTRAINT media_assets_source_storage_path_unique UNIQUE (source_storage_path),
  ADD CONSTRAINT media_assets_source_storage_path_length CHECK (
    source_storage_path IS NULL OR char_length(source_storage_path) BETWEEN 1 AND 400
  ),
  ADD CONSTRAINT media_assets_source_file_name_length CHECK (
    source_file_name IS NULL OR char_length(source_file_name) BETWEEN 1 AND 260
  ),
  ADD CONSTRAINT media_assets_source_content_type_allowed CHECK (
    source_content_type IS NULL OR source_content_type = ANY (ARRAY[
      'image/png','image/jpeg','image/webp','image/avif','image/gif',
      'image/bmp','image/heic','image/heif','image/tiff'
    ])
  ),
  ADD CONSTRAINT media_assets_source_size_limit CHECK (
    source_size_bytes IS NULL OR source_size_bytes BETWEEN 1 AND 31457280
  ),
  ADD CONSTRAINT media_assets_source_metadata_coherent CHECK (
    (source_storage_path IS NULL AND source_file_name IS NULL
      AND source_content_type IS NULL AND source_size_bytes IS NULL)
    OR
    (source_storage_path IS NOT NULL AND source_file_name IS NOT NULL
      AND source_content_type IS NOT NULL AND source_size_bytes IS NOT NULL)
  ),
  ADD CONSTRAINT media_assets_processing_mode_allowed CHECK (
    processing_mode IN ('legacy', 'original', 'normalized')
  ),
  ADD CONSTRAINT media_assets_focal_pair CHECK (
    (suggested_focal_x IS NULL AND suggested_focal_y IS NULL)
    OR
    (suggested_focal_x BETWEEN 0 AND 1 AND suggested_focal_y BETWEEN 0 AND 1)
  );

COMMENT ON COLUMN public.media_assets.source_storage_path IS
  'Private product-media-originals object path. Null only for pre-pipeline legacy rows.';
COMMENT ON COLUMN public.media_assets.processing_mode IS
  'legacy: pre-pipeline row; original: delivery master is unchanged; normalized: delivery master is converted/resized.';
COMMENT ON COLUMN public.media_assets.suggested_focal_x IS
  'Automated face/saliency focal suggestion in normalized 0..1 image coordinates.';

-- Register both Storage objects using server-verified metadata. A versioned RPC
-- keeps deployment rollout safe while older app instances still use v1.
CREATE OR REPLACE FUNCTION api.register_media_v2(
  p_path text,
  p_url text,
  p_file_name text,
  p_content_type text,
  p_size_bytes integer,
  p_width integer,
  p_height integer,
  p_source_path text,
  p_source_file_name text,
  p_source_content_type text,
  p_source_size_bytes integer,
  p_processing_mode text,
  p_suggested_focal_x numeric,
  p_suggested_focal_y numeric,
  p_actor uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_row public.media_assets%ROWTYPE;
BEGIN
  IF p_actor IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.staff_profiles WHERE user_id = p_actor AND is_active
  ) THEN
    RAISE EXCEPTION 'actor_not_authorized'
      USING DETAIL = 'An active acting user is required';
  END IF;

  IF p_content_type IS NULL OR p_content_type <> ALL (
    ARRAY['image/png','image/jpeg','image/webp','image/avif','image/gif']
  ) OR p_size_bytes IS NULL OR p_size_bytes NOT BETWEEN 1 AND 15728640 THEN
    RAISE EXCEPTION 'invalid_media_type'
      USING DETAIL = 'Invalid public delivery image metadata';
  END IF;

  IF p_source_content_type IS NULL OR p_source_content_type <> ALL (ARRAY[
    'image/png','image/jpeg','image/webp','image/avif','image/gif',
    'image/bmp','image/heic','image/heif','image/tiff'
  ]) OR p_source_size_bytes IS NULL OR p_source_size_bytes NOT BETWEEN 1 AND 31457280 THEN
    RAISE EXCEPTION 'invalid_source_type'
      USING DETAIL = 'Invalid private source image metadata';
  END IF;

  IF p_path IS NULL OR char_length(p_path) NOT BETWEEN 1 AND 400
    OR p_source_path IS NULL OR char_length(p_source_path) NOT BETWEEN 1 AND 400
    OR p_url IS NULL OR char_length(p_url) NOT BETWEEN 1 AND 1000
    OR p_file_name IS NULL OR char_length(p_file_name) NOT BETWEEN 1 AND 260
    OR p_source_file_name IS NULL OR char_length(p_source_file_name) NOT BETWEEN 1 AND 260
    OR p_width IS NULL OR p_height IS NULL OR p_width <= 0 OR p_height <= 0
    OR p_processing_mode IS NULL OR p_processing_mode NOT IN ('original', 'normalized')
    OR ((p_suggested_focal_x IS NULL) <> (p_suggested_focal_y IS NULL))
    OR (p_suggested_focal_x IS NOT NULL AND (
      p_suggested_focal_x NOT BETWEEN 0 AND 1 OR p_suggested_focal_y NOT BETWEEN 0 AND 1
    )) THEN
    RAISE EXCEPTION 'invalid_media_type'
      USING DETAIL = 'Invalid image catalogue metadata';
  END IF;

  INSERT INTO public.media_assets (
    storage_path, public_url, file_name, content_type, size_bytes, width, height,
    source_storage_path, source_file_name, source_content_type, source_size_bytes,
    processing_mode, suggested_focal_x, suggested_focal_y, created_by
  ) VALUES (
    p_path, p_url, p_file_name, p_content_type, p_size_bytes, p_width, p_height,
    p_source_path, p_source_file_name, p_source_content_type, p_source_size_bytes,
    p_processing_mode, p_suggested_focal_x, p_suggested_focal_y, p_actor
  )
  ON CONFLICT (storage_path) DO UPDATE SET
    public_url = EXCLUDED.public_url,
    file_name = EXCLUDED.file_name,
    content_type = EXCLUDED.content_type,
    size_bytes = EXCLUDED.size_bytes,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    source_storage_path = EXCLUDED.source_storage_path,
    source_file_name = EXCLUDED.source_file_name,
    source_content_type = EXCLUDED.source_content_type,
    source_size_bytes = EXCLUDED.source_size_bytes,
    processing_mode = EXCLUDED.processing_mode,
    suggested_focal_x = EXCLUDED.suggested_focal_x,
    suggested_focal_y = EXCLUDED.suggested_focal_y
  RETURNING * INTO v_row;

  INSERT INTO public.audit_logs (actor_id, action, target_type, target_id, metadata)
  VALUES (
    p_actor, 'media.uploaded', 'media_assets', v_row.id::text,
    jsonb_build_object(
      'path', p_path,
      'source_path', p_source_path,
      'size_bytes', p_size_bytes,
      'source_size_bytes', p_source_size_bytes,
      'processing_mode', p_processing_mode
    )
  );

  RETURN to_jsonb(v_row);
END;
$$;

REVOKE ALL ON FUNCTION api.register_media_v2(
  text, text, text, text, integer, integer, integer, text, text, text, integer,
  text, numeric, numeric, uuid
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION api.register_media_v2(
  text, text, text, text, integer, integer, integer, text, text, text, integer,
  text, numeric, numeric, uuid
) TO service_role;

-- Product and banner references both count as usage in the admin library.
CREATE OR REPLACE FUNCTION api.list_media(p_actor uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE v_rows jsonb;
BEGIN
  IF p_actor IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.staff_profiles WHERE user_id = p_actor AND is_active
  ) THEN
    RAISE EXCEPTION 'actor_not_authorized'
      USING DETAIL = 'An active acting user is required';
  END IF;

  SELECT COALESCE(
    jsonb_agg(
      to_jsonb(m) || jsonb_build_object(
        'usage_count', COALESCE(pu.cnt, 0) + COALESCE(bu.cnt, 0)
      )
      ORDER BY m.created_at DESC
    ),
    '[]'::jsonb
  )
  INTO v_rows
  FROM public.media_assets m
  LEFT JOIN LATERAL (
    SELECT count(*)::int AS cnt FROM public.product_media pm WHERE pm.url = m.public_url
  ) pu ON true
  LEFT JOIN LATERAL (
    SELECT count(*)::int AS cnt FROM public.banners b WHERE b.image_url = m.public_url
  ) bu ON true;

  RETURN v_rows;
END;
$$;

REVOKE ALL ON FUNCTION api.list_media(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION api.list_media(uuid) TO service_role;

-- Versioned delete returns both object paths. It preserves the latest product
-- gallery and banner in-use guards from the existing v1 function.
CREATE OR REPLACE FUNCTION api.delete_media_v2(p_id uuid, p_actor uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_path text;
  v_source_path text;
  v_url text;
BEGIN
  IF p_actor IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.staff_profiles WHERE user_id = p_actor AND is_active
  ) THEN
    RAISE EXCEPTION 'actor_not_authorized'
      USING DETAIL = 'An active acting user is required';
  END IF;

  SELECT storage_path, source_storage_path, public_url
    INTO v_path, v_source_path, v_url
  FROM public.media_assets
  WHERE id = p_id
  FOR UPDATE;
  IF v_path IS NULL THEN
    RAISE EXCEPTION 'media_not_found' USING DETAIL = 'Media asset not found';
  END IF;

  IF EXISTS (SELECT 1 FROM public.product_media WHERE url = v_url) THEN
    RAISE EXCEPTION 'media_in_use'
      USING DETAIL = 'This image is attached to one or more product galleries';
  END IF;
  IF EXISTS (SELECT 1 FROM public.banners WHERE image_url = v_url) THEN
    RAISE EXCEPTION 'media_in_use'
      USING DETAIL = 'This image is used by one or more homepage banners';
  END IF;

  DELETE FROM public.media_assets WHERE id = p_id;

  INSERT INTO public.audit_logs (actor_id, action, target_type, target_id, metadata)
  VALUES (
    p_actor, 'media.deleted', 'media_assets', p_id::text,
    jsonb_build_object('path', v_path, 'source_path', v_source_path)
  );

  RETURN jsonb_build_object('path', v_path, 'source_path', v_source_path);
END;
$$;

REVOKE ALL ON FUNCTION api.delete_media_v2(uuid, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION api.delete_media_v2(uuid, uuid) TO service_role;
